version: '3.1'

services:
  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile


  movieservice:
    image: ${DOCKER_REGISTRY-}movieservice
    build:
      context: .
      dockerfile: MovieService/Dockerfile


  cartservice:
    image: ${DOCKER_REGISTRY-}cartservice
    build:
      context: .
      dockerfile: CartService/Dockerfile

